apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    run: nodeimage
  name: nodeimage
spec:
  replicas: 3
  selector:
    matchLabels:
      run: nodeimage
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: nodeimage
    spec:
      containers:
        - image: joekings2k/nodeimage:1.0
          imagePullPolicy: Always
          name: nodeimage
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 2m
              memory: 30Mi
            requests:
              cpu: 1m
              memory: 10Mi
      imagePullSecrets:
        - name: icr
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
